name: CI

on:
  push:
    branches:
      - dev
    paths:
      - "**ci.yml"
      - "**.hpp"
      - "**.cpp"
      - "**CMakeLists.txt"
  pull_request:
    branches:
      - dev
    paths:
      - "**ci.yml"
      - "**.hpp"
      - "**.cpp"
      - "**CMakeLists.txt"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: ubuntu-22.04,
              arch: x64,
              binary_path: saber,
              output_name: saber-linux-x64,
            }
          - {
              os: windows-2022,
              arch: x64,
              binary_path: Release/saber.exe,
              output_name: saber-windows-x64.exe,
            }
          - {
              os: windows-2022,
              arch: x86,
              binary_path: Release/saber.exe,
              output_name: saber-windows-x86.exe,
            }

    name: build-${{ matrix.config.os }}-${{ matrix.config.arch }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++-10 libssl-dev ninja-build rpm zlib1g-dev

      - name: Add MSBuild to PATH (Windows)
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1

      - name: Configure CMake (Linux)
        if: runner.os == 'Linux'
        run: cmake -S . -B build -G Ninja

      - name: Configure CMake (Windows x64)
        if: runner.os == 'Windows' && matrix.config.arch == 'x64'
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -T host=x64

      - name: Configure CMake (Windows x86)
        if: runner.os == 'Windows' && matrix.config.arch == 'x86'
        run: cmake -S . -B build -D net_FORCE_BUILD_OPENSSL=ON -G "Visual Studio 17 2022" -A Win32 -T host=x86

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.config.output_name }}
          path: ./build/${matrix.config.binary_path}
          if-no-files-found: error

  release:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, arch: x64, binary_name: saber-linux-x64 }
          - {
              os: windows-latest,
              arch: x64,
              binary_name: saber-windows-x64.exe,
            }
          - {
              os: windows-latest,
              arch: x86,
              binary_name: saber-windows-x86.exe,
            }

    name: release-${{ matrix.config.os }}-${{ matrix.config.arch }}
    runs-on: ${{ matrix.config.os }}
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: dev

      - name: Create Draft Release
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: true
          draft: false
          commit: ${{ github.sha }}
          tag: ${{ steps.semver.outputs.next }}-dev
          name: ${{ steps.semver.outputs.next }}-dev
          body: "*pending*"
          token: ${{ github.token }}

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.next }}-dev
          writeToFile: false

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: true
          allowUpdates: true
          draft: false
          makeLatest: true
          commit: ${{ github.sha }}
          tag: ${{ steps.semver.outputs.next }}-dev
          name: ${{ steps.semver.outputs.next }}-dev
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.config.binary_name }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: ${{ matrix.config.binary_name }}
          tag: ${{ steps.semver.outputs.next }}-dev
